# Copyright (c) 2019-2020 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

# Main azure-pipelines configuration for the OpenXR-SDK repo.

trigger:
  branches:
    include:
      - "*"

stages:
  - stage: Build
    jobs:
      - template: build_jobs.yml
